### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by jdmg94** [Shopify/restyle#20]
Are there any plans to make this library platform agnostic?
I love the API and I would like to bring it to the web, this would also make it compatible with `react-native-web` and `expo` web

**Comment by JoelBesada** [comment]
Would definitely love to have web support, but no concrete plans right now when that would happen. I think the main things to build to add support would be:

* Add a way to pass the `style` prop object through a CSS-in-JS processor (e.g. styled-components or StyleSheet from react-native-web) to get css classes instead of inline styles. 
* Generate responsive styles as media-query definitions instead of changing them through window resize listeners. 
* Figure out any discrepancies between RN and web styles. For example, `paddingVertical` is not a valid css rule for web, and `display: flex` needs to be specified when using flex rules. Maybe this is something react-native-web Stylesheet does for you already.
* Switch to platform agnostic versions of Text and View components.

There might be more that I'm missing here, but overall I think it should be very doable.

**Comment by arrygoo** [comment]
@JoelBesada 

* I could be wrong but I don't think you need to use platform agnostic versions of `View` and `Text` to have it work with `react-native-web`. I gave it a quick test with `expo web` and at least the basic example work fine. Similarly regarding things like `paddingVertical` and `display: flex` I see that they're already being translated correctly when ran on web. Any APIs used that are in this list should be good to use on `react-native-web` without having to take any extra steps. 

Here's the sample code: 

https://github.com/arrygoo/restyle-expo-web-example

<img width="995" alt="Screen Shot 2020-07-16 at 1 45 11 PM" src="https://user-images.githubusercontent.com/965429/87704611-acee9880-c76a-11ea-88b6-5ca9d10d8d6b.png">

<img width="952" alt="Screen Shot 2020-07-16 at 1 56 10 PM" src="https://user-images.githubusercontent.com/965429/87705584-1de28000-c76c-11ea-9402-57d008d1b9f2.png">

**Comment by JoelBesada** [comment]
@arrygoo Oh, that's interesting, thanks for creating this example! That should cover the last two bullet points in my comment above, I think there's still some work that needs to be done to pass styles through `StyleSheet` so `react-native-web` can create CSS classes instead of inlining everything on each component. This is mostly relevant for server-side rendering ([which RNW seems to support](https://github.com/necolas/react-native-web/blob/master/packages/docs/src/guides/server-side-rendering.stories.mdx)), but if all you need is a purely client-side rendered web app then I guess Restyle should already be usable in its current state.

**Comment by nandorojo** [comment]
Hey I've been working on [https://github.com/dripsy](dripsy), a responsive design system for RNW. I got media queries/responsive styles to work with server side rendering, but it required using `@artsy/fresnel` under the hood. 

React Native Web doesn't support the `className` attribute, so I couldn't use `styles-components`'s simple API for media queries, sadly. If you end up coming up with a better solution for RNW + SSR + media queries, I would love to hear!
