### ISSUE TITLE
React native testing library support

### ISSUE THREAD

**Issue by thozh** [Shopify/restyle#39]
I'm trying to unit test components with restyle on a React Native app but with no success 😢 

```js
// Box.js
import { createBox } from "@shopify/restyle";
import { Theme } from "./theme";

const Box = createBox<Theme>();

export default Box;
```

This is the line where the test throws an error : 
```js
const {getByText, getByPlaceholder} = render(
    <ThemeProvider theme={theme}>
      <Box />
    </ThemeProvider>
  );
``` 

```sh
  ● Test suite failed to run

    Invariant Violation: __fbBatchedBridgeConfig is not set, cannot invoke native modules

      at invariant (../node_modules/@shopify/restyle/node_modules/invariant/invariant.js:40:15)
      at Object.<anonymous> (../node_modules/@shopify/restyle/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:169:3)
      at Object.<anonymous> (../node_modules/@shopify/restyle/node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:13:23)
```

Any ideas what does that mean ?

**Comment by jdmg94** [comment]
you might want to look into `@testing-library/react-native` as they have announced they're merging: 

https://callstack.com/blog/merge-of-react-native-testing-libraries/

**Comment by Charly6596** [comment]
Hey there, I'm currently using `@shopify/restyle` with `@testing-library/react-native`, all I had to do is to create a file (`component-test-utils.tsx` in my case) and export everything from `@testing-library/react-native` overwritting the `render` export with a function that takes the same arguments as `render` but uses a predefined wrapper (hence the wrapper is passed as an option)
You can add any other provider your tests need to the Providers function component. In your tests, instead of importing from `@testing-library/react-native`, you would have to import from your own file instead
`component-test-utils.tsx`
```ts
import * as React from "react";
import { render } from "@testing-library/react-native";
import { ThemeProvider } from "@shopify/restyle";
import theme from "../Theme";

type ProvidersProps = {
  children?: React.ReactNode;
};

const Providers = ({ children }: ProvidersProps) => {
  return <ThemeProvider theme={theme}>{children}</ThemeProvider>;
};

const customRender: typeof render = (component, options) => {
  return render(component, { wrapper: Providers, ...options });
};

export * from "@testing-library/react-native";
export { customRender as render };
```
`Box.spec.tsx`
```ts
import * as React from "react";
import Box from "../Box";
import { render } from "./component-test-utils";

describe("Box component", () => {
  it("renders", () => {
    const testID = "testID";
    const { getByTestId } = render(<Box testID={testID} />);
    expect(getByTestId(testID)).toBeTruthy();
  });
});
```
It works for me, hope it helps. I don't know if this would solve your problem tho, since I didn't face it

**Comment by drmas** [comment]
@thozh I'll close this issue for now, let me know if @Charly6596  didn't work for you and then we can re-open it back
