### ISSUE TITLE
createText missing layout props

### ISSUE THREAD

**Issue by matthewcarlreetz** [Shopify/restyle#68]
I'd like for layout props to be exposed within `createText` so that I can use it like this
```
 <Text
    width={260}
    variant="header"
 >
```
Would you accept a PR with the addition or was it intentionally left out?

**Comment by flexbox** [comment]
Hey @matthewcarlreetz 
You can't use this `out-of-the-box` because `width` is not valid `TextStyle` props
https://reactnative.dev/docs/text-style-props

It's still doable if you want:
1. create a `Text.ts` component
2. use all the custom props you want to include like
```typescript
// src/components/Text.tsx
import {
	ColorProps,
	layout,
	LayoutProps,
	typography,
	TypographyProps,
	useRestyle,
} from '@shopify/restyle'
import { color } from '@storybook/addon-knobs'
import React from 'react'
import { Text } from 'react-native'
import { Theme } from '~/theme/theme'

const restyleFunctions = [color, typography, layout]    <------ add layout here

type Props = ColorProps<Theme> &
	LayoutProps<Theme> &    <------ and here
	TypographyProps<Theme> & {
		children: React.ReactNode
	}

export const Text = ({ children, ...rest }: Props) => {
	const props = useRestyle(restyleFunctions, rest)

	return <Text {...props}>{children}</Text>
}

```

BUT I would not recommend it.
If you onboard a new team member he probably would not understand why it's possible to specify `width` on a `Text`

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
